apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  labels:
    app: {{.Values.app.name}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.pv.capacity}}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wordpress-pv-claim
  labels:
    app: {{.Values.app.name}}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: {{.Values.pv.capacity}}
---