apiVersion: v1
kind: Service
metadata:
  name: {{.Values.servicemysql.name}}
  labels:
    app: {{.Values.app.name}}
spec:
  ports:
    - port: {{ .Values.servicemysql.port }}
  selector:
    app: {{.Values.app.name}}
    tier: {{.Values.imagemysql.tier}}
  clusterIP: None
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.servicewordpress.name }}
  labels:
    app: {{.Values.app.name}}
spec:
  type: {{.Values.servicewordpress.type}}
  ports:
    - port: {{ .Values.servicewordpress.port }}
  selector:
    app: {{.Values.app.name}}
    tier: {{.Values.imagewordpress.tier}}
---